export const states = [
    "Andaman and Nicobar Islands",
    "Gujarat",
    "Assam",
    "Daman and Diu",
    "Chhattisgarh",
    "Dadra and Nagar Haveli",
    "West Bengal",
    "Jammu and Kashmir",
    "Uttar Pradesh",
    "Uttarakhand",
    "Punjab",
    "Haryana",
    "Tripura",
    "Lakshadweep",
    "Himachal Pradesh",
    "Goa",
    "Jharkhand",
    "Rajasthan",
    "Telangana",
    "Arunachal Pradesh",
    "Odisha",
    "Delhi",
    "Puducherry",
    "Mizoram",
    "Andhra Pradesh",
    "Karnataka",
    "Maharashtra",
    "Meghalaya",
    "Kerala",
    "Nagaland",
    "Ladakh",
    "Bihar",
    "Manipur",
    "Tamil Nadu",
    "Madhya Pradesh",
    "Sikkim",
    "Chandigarh"
    ];