import localFont from "next/font/local";
import "../styles/globals.css";
import StoreProvider from "./StoreProvider";
import { ToastContainer } from "react-toastify";

import "bootstrap/dist/css/bootstrap.min.css";
import "react-datepicker/dist/react-datepicker.css";
import "react-toastify/dist/ReactToastify.css";

/* React Input Phone Number Css Module */
import "react-phone-input-2/lib/style.css";

import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./Error";
import { ApolloProviderWrapper } from "../lib/Apollo/ApolloProviderWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Mentor Portal App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <>
          <ErrorBoundary fallback={<Error />}>
            <StoreProvider>
              <ApolloProviderWrapper>
                {children}
              </ApolloProviderWrapper>
            </StoreProvider>
          </ErrorBoundary>

          <ToastContainer />
        </>
      </body>
    </html>
  );
}
